#include <stdio.h>
#include <stdlib.h>

/*
 
 Vahit Buğra YEŞİLKAYNAK
 150150019
 BIL105E Homework 2
 
 */

static long range1, range2, range3, range4, range5 = 0;

void mid_rng(long *number){
	long sqr = *number * *number;
    
    // It is easy to understand these if statements
    // Basically I'm checking if it is 5 or less digits long
    // Then if it has more digits I test it for 6 and 7 and so on
    // Since I know it can be max 10 digits I stop there
    // Since I want the middle number I wrote algorithms for each number of digits
    // This is not the best way to do it I could write a code that it would find the middle
    // For even 10000 digit numbers but since we don't have the variety I did it like this
    
	if (sqr / 100000 == 0){ // 5 zeros if the number is 5 or less digits
		*number = sqr;
		return;
	}
	else if (sqr / 1000000 == 0) { // 6 zeros if the number  is 6 digits
		long temp1 = sqr / 100000;
		long temp2 = sqr - temp1 * 100000;
		*number = temp2;
		return;
	}
	else if (sqr / 10000000 == 0) { // 7 zeros if the number  is 7 digits
		long temp1 = sqr / 10;
		long temp2 = temp1 / 100000;
		temp1 -= temp2 * 100000;
		*number = temp1;
		return;
	}
	else if (sqr / 100000000 == 0) { // 8 zeros if the number  is 8 digits
		long temp1 = sqr / 100;
		long temp2 = temp1 / 100000;
		temp1 -= temp2 * 100000;
		*number = temp1;
		return;
	}
	else if (sqr / 1000000000 == 0) { // 9 zeros if the number  is 9 digits
		long temp1 = sqr / 100;
		long temp2 = temp1 / 100000;
		temp1 -= temp2 * 100000;
		*number = temp1;
		return;
	}
	else if (sqr / 10000000000 == 0) { // 10 zeros if the number is 10 digits 
		long temp1 = sqr / 1000;
		long temp2 = temp1 / 100000;
		temp1 -= temp2 * 100000;
		*number = temp1;
		return;
	}
}

void lsd_rng(long *number){
    
    // This algorithm is rather simple really
    
	long product = 73 * *number;
	long temp = product / 100000;
	*number = product  - (temp * 100000);
}

void print_histogram(int which, long samples){
    
    // This function takes some value then prints a histogram
    
    long i, numerator, PRange1, PRange2, PRange3, PRange4, PRange5;
    numerator = range1 + range2 + range3 + range4 + range5;
    PRange1 = (range1 * 100) / numerator;
    PRange2 = (range2 * 100) / numerator;
    PRange3 = (range3 * 100) / numerator;
    PRange4 = (range4 * 100) / numerator;
    PRange5 = (range5 * 100) / numerator;
    
    printf("$ %ld random numbers were generated by using ", samples);
    if(which == 1){printf("MID-PRNG:\n");}
    else if(which == 2){printf("LSD_PRNG:\n");}
    printf("  1..100: ");
    for (i = 0; i < PRange1; ++i) {
        printf("*");
    }
    printf("(%ld%%)\n", PRange1);
    
    printf("101..200: ");
    for (i = 0; i < PRange2; ++i) {
        printf("*");
    }
    printf("(%ld%%)\n", PRange2);
    
    printf("201..300: ");
    for (i = 0; i < PRange3; ++i) {
        printf("*");
    }
    printf("(%ld%%)\n", PRange3);
    
    printf("301..400: ");
    for (i = 0; i < PRange4; ++i) {
        printf("*");
    }
    printf("(%ld%%)\n", PRange4);
    
    printf("401..500: ");
    for (i = 0; i < PRange5; ++i) {
        printf("*");
    }
    printf("(%ld%%)\n", PRange5);
}

void take_samples(int which, long samples, long seed){
    
    // This function uses rng functions and counts the ranges
    
	if(which == 1)
	{
		long currSamples;
		for(currSamples = 0; currSamples < samples; ++currSamples)
		{
			mid_rng(&seed);
			long map = seed % 500;
			if (map >= 1 && map < 101){
				++range1;
			}
			else if (map >= 101 && map < 201){
				++range2;
			}	
			else if (map >= 201 && map < 301){
				++range3;
			}			
			else if (map >= 301 && map < 401){
				++range4;
			}			
			else if (map >= 401 && map < 500){
				++range5;
			}
		}
	}

	if(which == 2)
	{
		long currSamples;
		for(currSamples = 0; currSamples < samples; ++currSamples)
		{
			lsd_rng(&seed);
			long map = seed % 500;
			if (map >= 1 && map < 101){
				++range1;
			}
			else if (map >= 101 && map < 201){
				++range2;
			}
			else if (map >= 201 && map < 301){
				++range3;
			}
			else if (map >= 301 && map < 401){
				++range4;
			}
			else if (map >= 401 && map < 500){
				++range5;
			}
		}
	}
}

int main(){
	printf("$ Which PRNG Algorithm?\n");
	printf("\t1. MID-PRNG\n");
	printf("\t2. LSD-PRNG\n");
	printf("$ ");
	int which;
	scanf("%d", &which);
	printf("$ Enter the seed\n");
	long seed;
	printf("$ ");
	scanf("%ld", &seed);

	while ((which == 2) && ((seed - ((seed / 10) * 10) == 5) || seed % 2 == 0))
	{
		printf("$ The seed is not acceptable enter a new seed\n");
		printf("$ ");
		scanf("%ld", &seed);
	}

	printf("$ Enter Number of Samples\n");
	printf("$ ");
	long samples;
	scanf("%ld", &samples);
	take_samples(which, samples, seed);
    print_histogram(which, samples);
} 